### ISSUE TITLE
怎么用它翻墙？

### ISSUE THREAD

**Issue by briteming** [lianglixin/SKSocks#2]
能详细说明一下吗

**Comment by tedlife** [comment]
长期稳定翻墙还是花点钱吧，折腾免费工具或服务得浪费多少时间，这里有篇文章，有免费的有付费的，可以参考参考 https://wordpresshi.com/shawdowsocks-centos/

**Comment by ghost** [comment]
https://www.die.lu/core/index.php/2019/03/16/76/
此处有详细说明，如有疑问可以再开issues
